/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElCard: (typeof import("element-plus/es"))["ElCard"];
    ElDropdown: (typeof import("element-plus/es"))["ElDropdown"];
    ElDropdownItem: (typeof import("element-plus/es"))["ElDropdownItem"];
    ElDropdownMenu: (typeof import("element-plus/es"))["ElDropdownMenu"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElSwitch: (typeof import("element-plus/es"))["ElSwitch"];
    IEpInfoFilled: (typeof import("~icons/ep/info-filled"))["default"];
    IEpSuccessFilled: (typeof import("~icons/ep/success-filled"))["default"];
    IEpWarningFilled: (typeof import("~icons/ep/warning-filled"))["default"];
    IEpWarnTriangleFilled: (typeof import("~icons/ep/warn-triangle-filled"))["default"];
    LanguageSelect: (typeof import("./../components/LanguageSelect/index.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    SvgIcon: (typeof import("./../components/SvgIcon/index.vue"))["default"];
  }
}
